import {chromium} from 'file:///C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:3000',{waitUntil:'networkidle'});await page.getByRole('heading',{name:'德國、荷蘭之旅',exact:true}).waitFor();
const tab=name=>page.locator('.j-tabs').getByRole('button',{name,exact:true});
await page.screenshot({path:'outputs/qa-overview.png',fullPage:true});
await tab('每日').click();await page.locator('#day-select').selectOption('7');assert.match(await page.locator('.j-day').innerText(),/Delft/);assert.equal(await page.locator('.j-day').count(),1);await page.getByRole('button',{name:'下一天 →',exact:true}).click();assert.equal(await page.locator('#day-select').inputValue(),'8');await page.locator('#day-select').selectOption('9');assert.match(await page.locator('.j-day').innerText(),/梵谷/);await page.screenshot({path:'outputs/qa-daily.png',fullPage:true});
await tab('記帳').click();await page.locator('.j-total').waitFor();assert.match(await page.locator('.j-total').innerText(),/100,098/);
await page.getByLabel('明細',{exact:true}).fill('測試火車票');await page.getByLabel('金額',{exact:true}).fill('12.5');await page.getByLabel('換算匯率',{exact:true}).fill('37');await page.getByRole('button',{name:'加進帳本',exact:true}).click();assert.match(await page.locator('.j-total').innerText(),/100,560.5/);await page.screenshot({path:'outputs/qa-ledger.png',fullPage:true});
await page.reload({waitUntil:'networkidle'});await tab('記帳').click();assert.match(await page.locator('.j-total').innerText(),/100,560.5/);await page.locator('summary').filter({hasText:'餐飲'}).click();await page.getByRole('button',{name:'編輯',exact:true}).click();await page.getByLabel('金額',{exact:true}).fill('10');await page.getByRole('button',{name:'儲存修改',exact:true}).click();assert.match(await page.locator('.j-total').innerText(),/100,468/);await page.getByRole('button',{name:'刪除',exact:true}).click();await page.getByRole('button',{name:'確認刪除',exact:true}).click();assert.match(await page.locator('.j-total').innerText(),/100,098/);
await tab('行李').click();const n=await page.locator('.j-pack-row').count();await page.getByLabel('新增物品',{exact:true}).fill('測試備用眼鏡');await page.getByRole('button',{name:'加入行李清單',exact:true}).click();assert.equal(await page.locator('.j-pack-row').count(),n+1);await page.getByRole('checkbox',{name:'測試備用眼鏡'}).check();await page.getByRole('button',{name:'刪除 測試備用眼鏡',exact:true}).click();assert.equal(await page.locator('.j-pack-row').count(),n);
await tab('與 Claude 共編').click();const dl=page.waitForEvent('download');await page.getByRole('button',{name:'匯出完整 JSON',exact:true}).click();await(await dl).saveAs('outputs/qa-roundtrip.json');const p=JSON.parse(fs.readFileSync('outputs/qa-roundtrip.json','utf8'));assert.equal(p.expenses.length,3);assert.equal(p.packing.length,n);p.notes['2026-11-19']='匯入測試';fs.writeFileSync('outputs/qa-import.json',JSON.stringify(p));await page.locator('input[type=file]').setInputFiles('outputs/qa-import.json');await page.waitForTimeout(200);await tab('每日').click();await page.locator('#day-select').selectOption('7');assert.equal(await page.getByLabel('當日備註').inputValue(),'匯入測試');
for(const width of [375,430,1080]){await page.setViewportSize({width,height:900});for(const name of ['快覽','每日','記帳','住宿','城市的味道','行李','要先下載的app']){await tab(name).click();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,`${name} overflow ${width}`);}}
await tab('住宿').click();await page.locator('.j-gallery').first().scrollIntoViewIfNeeded();await page.screenshot({path:'outputs/qa-stays.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: daily paging, ledger CRUD + FX + persistence, packing CRUD, JSON roundtrip, responsive widths, no JS errors');await browser.close();
