import assert from 'node:assert/strict';
import fs from 'node:fs';
import {initialDraft,validateDraft,markdown,migrateDraft,travelers,flights} from './lib/trip.ts';
import {foodLists} from './lib/foods.ts';
import {climate,weatherNotes} from './lib/weather.ts';
import {estimateBudget,lodgingQuotes} from './lib/budget.ts';
const d=structuredClone(initialDraft);d.notes['2026-11-19']='保留備註';
assert(validateDraft(d));assert(!validateDraft({...d,days:[null,...d.days.slice(1)]}));
assert.equal(d.days.length,14);assert.equal(d.days.filter(x=>x.stay).length,10);
assert.equal(travelers.length,5);assert.equal(estimateBudget().lodging,100098/5);
assert(d.stays[2].name.includes('Cityden'));assert.equal(lodgingQuotes[2].totalTwd,43000);
assert(d.days.filter(x=>x.date<'2026-11-17'||x.date>'2026-11-23').every(x=>!x.rain));
assert(foodLists.every(c=>c.items.every(f=>f.name&&f.dish&&new URL(f.mapsUrl).hostname==='www.google.com')));
assert.equal(climate.length,2);assert(markdown(d).includes('保留備註'));
const old={...d,planRevision:3};assert.equal(migrateDraft(old).notes['2026-11-19'],'保留備註');
const p=fs.readFileSync('app/page.tsx','utf8');assert.equal(p.slice(p.indexOf(' const day=' )).trim(),fs.readFileSync('mobile-view.part','utf8').trim());
assert(!p.includes('value="sources"'));assert(!fs.readFileSync('app/budget.tsx','utf8').includes('travel-budget.txt'));
fs.writeFileSync('exports/德荷旅遊.md',markdown(initialDraft));
fs.writeFileSync('exports/德荷旅遊.json',JSON.stringify({...initialDraft,reference:{travelers,flights,foodLists,climate,weatherNotes,lodgingQuotes,budget:estimateBudget()}},null,2));
console.log('PASS: 14 days, 10 nights, 5 travelers, Cityden, budget, Netherlands-only rain, Maps fields, import validation, notes migration, template synchronization, exports.');
