'use client';
import {useEffect,useRef,useState} from 'react';
import {initialPlan,mapUrl,migrateLegacy,parsePlan,planMarkdown,type Plan} from '@/lib/journey';
import {climate,weatherNotes} from '@/lib/weather';
import Gallery from './gallery';
import PlaceStories from './place-stories';
import MedicaCard from './medica-card';
import Ledger from './ledger';
import Packing from './packing';
import Shopping from './shopping';
import './journey.css';
const KEY='de-nl-travel-2026-v6';
const tabs=[['overview','🧭','快覽'],['daily','🗓️','每日'],['food','🍽️','城市的味道'],['stays','🛏️','住宿'],['flights','🚆','交通'],['ledger','💳','記帳'],['packing','🧳','行李'],['weather','🌦️','天氣'],['apps','📱','要下載的app']];
const appLinks:Record<string,string>={'DB Navigator':'https://www.bahn.de/service/mobile/db-navigator','Rheinbahn':'https://www.rheinbahn.com/','Buienradar':'https://www.buienradar.nl/','NS':'https://www.ns.nl/en/travel-information/ns-app','9292':'https://9292.nl/en/','GVB':'https://www.gvb.nl/en','Google Maps':'https://maps.google.com/','Google 翻譯':'https://translate.google.com/','Reclamefolder':'https://www.reclamefolder.nl/','WhatsApp':'https://www.whatsapp.com/download'};
const appIcons:Record<string,string>={'DB Navigator':'DB','Rheinbahn':'R','Buienradar':'☂','NS':'↔','9292':'9292','GVB':'GVB','Google Maps':'⌖','Google 翻譯':'文A','WhatsApp':'☎'};

function MapLink({query}:{query:string}){return <a className="j-link" href={mapUrl(query)} target="_blank" rel="noreferrer">Google Maps ↗</a>}

type JourneyTheme='germany'|'netherlands'|'neutral';
function journeyTheme(date:string):JourneyTheme{
 if(date>='2026-11-13'&&date<='2026-11-17')return 'germany';
 if(date>='2026-11-18'&&date<='2026-11-23')return 'netherlands';
 return 'neutral';
}
const themeLabel:Record<JourneyTheme,{country:string;note:string}>={
 germany:{country:'DEUTSCHLAND',note:'Rhein · Bauhaus · Industry'},
 netherlands:{country:'NEDERLAND',note:'Canals · De Stijl · Light'},
 neutral:{country:'ON THE WAY',note:'Transit · Flight · Home'}
};
export default function Journey(){
 const [plan,setPlan]=useState<Plan>(initialPlan),[tab,setTab]=useState('overview'),[selected,setSelected]=useState(1),[ready,setReady]=useState(false),[status,setStatus]=useState(''),[canSave,setCanSave]=useState(true),[city,setCity]=useState('阿姆斯特丹'),[foodView,setFoodView]=useState('restaurants');const file=useRef<HTMLInputElement>(null),panel=useRef<HTMLElement>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw){const saved=JSON.parse(raw);if(saved.planRevision<8&&!localStorage.getItem(KEY+'-before-v8'))localStorage.setItem(KEY+'-before-v8',raw);setPlan(parsePlan(saved));}else{const old=localStorage.getItem('de-nl-travel-2026-v1');if(old){localStorage.setItem(KEY+'-legacy-backup',old);setPlan(migrateLegacy(JSON.parse(old)));}}}catch{setCanSave(false);setStatus('無法載入本機資料，原檔已保留；請先下載原始備份。');}setReady(true);},[]);
 function update(next:Plan){setPlan(next);if(!canSave){setStatus('修改暫存於此頁，請匯出 JSON 保存。');return;}try{localStorage.setItem(KEY,JSON.stringify(next));setStatus('已儲存至此瀏覽器');}catch{setStatus('儲存空間不足，請立即匯出 JSON 保存修改。');}}
 function download(text:string,name:string,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function exportPlan(kind:'json'|'md'){download(kind==='json'?JSON.stringify(plan,null,2):planMarkdown(plan),'德荷旅遊-共編.'+kind,kind==='json'?'application/json':'text/markdown;charset=utf-8');setStatus('下載檔已準備好');}
 async function importPlan(f?:File){if(!f)return;try{if(f.size>5000000)throw Error('JSON 檔案超過 5 MB');const next=parsePlan(JSON.parse(await f.text()));download(JSON.stringify(plan,null,2),'德荷旅遊-匯入前備份.json');update(next);setStatus('已匯入，並下載匯入前的備份。');}catch(e){setStatus('未匯入：'+(e instanceof Error?e.message:'格式錯誤'));}if(file.current)file.current.value='';}
 function changeTab(id:string){setTab(id);if(id==='food')setFoodView('restaurants');setTimeout(()=>panel.current?.scrollIntoView({block:'start'}),0);}
 function chooseDay(i:number){setSelected(i);setTimeout(()=>panel.current?.scrollIntoView({block:'start'}),0);}
 const d=plan.days[selected],photos=(names:string[])=>names.map(n=>plan.photos[n]).filter(Boolean),food=plan.reference.foodLists.find(c=>c.city===city);
 return <main className="journey"><header className="j-hero"><div className="j-hero-text"><p className="j-kicker">NOVEMBER 12—25, 2026</p><h1>德國、荷蘭之旅</h1><p className="j-intro">走在萊茵河畔的微風晨光裡，漫步到荷蘭悠閒的運河街景，穿梭在色彩繽紛的露天攤位間，嚐上一口熱騰騰的美味，最美好的假期記憶，就是這麼簡單。</p><p className="j-travelers">益萁 · 耘欣 · 靖宜 · 靖枝 · 玉穎</p></div><figure className="j-hero-photo"><img src={plan.photos['荷蘭11月 照片']} alt="阿姆斯特丹秋日運河" fetchPriority="high"/><figcaption className="j-photo-caption">📍 阿姆斯特丹・秋日運河</figcaption></figure></header><nav className="j-tabs" aria-label="旅行手冊選單">{tabs.map(([id,icon,label])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>changeTab(id)}><span aria-hidden="true">{icon}</span>{label}</button>)}</nav><section ref={panel} id="journey-panel" className="j-panel" aria-label={tabs.find(t=>t[0]===tab)?.[2]}>
 {tab==='overview'&&<section><p className="j-kicker">THE JOURNEY AT A GLANCE</p><h2>🧭 快覽</h2><div className="j-route">{plan.stays.map((s,i)=><article key={s.city}><span>0{i+1}</span><h3>{s.city}</h3><p>{s.checkIn.slice(5)} — {s.checkOut.slice(5)} · {s.nights} 晚</p></article>)}</div><p className="j-muted">時間皆為當地時間。交通與景點時段是行程安排，依實際訂票確認。</p><div className="j-overview">{plan.days.map((day,i)=><button key={day.date} onClick={()=>{setSelected(i);changeTab('daily');}}><time>{day.date.slice(5).replace('-','/')}<small>週{day.weekday}</small></time><span><strong>{day.city}</strong><span>{day.title}</span></span><b>→</b></button>)}</div><MedicaCard/><h3>🎟️ 先訂好，出發就輕鬆</h3><div className="j-grid">{plan.reference.ticketDeadlines.map(t=><article className="j-card" key={t.name}><h4>{t.name}</h4><p>{t.detail}</p><a className="j-link" target="_blank" rel="noreferrer" href={t.url}>前往預約／購票 ↗</a></article>)}</div></section>}
 {tab==='daily'&&<section className={`j-country-theme theme-${journeyTheme(d.date)}`}><div className="j-day-controls"><label className="j-sr" htmlFor="day-select">查看日期</label><select id="day-select" value={selected} onChange={e=>chooseDay(Number(e.target.value))}>{plan.days.map((day,i)=><option value={i} key={day.date}>{day.date.slice(5).replace('-','/')} 週{day.weekday} · {day.city}</option>)}</select><div className="j-actions"><button disabled={selected===0} onClick={()=>chooseDay(selected-1)}>← 前一天</button><button disabled={selected===plan.days.length-1} onClick={()=>chooseDay(selected+1)}>下一天 →</button></div></div><div key={d.date} className="j-day"><div className="j-country-mark"><span>{themeLabel[journeyTheme(d.date)].country}</span><small>{themeLabel[journeyTheme(d.date)].note}</small></div><p className="j-kicker">DAY {String(selected+1).padStart(2,'0')} / {d.date} · 週{d.weekday}</p><h2>{d.title}</h2><p className="j-city">{d.city}</p><Gallery key={d.date} images={photos((plan.dayPhotos as Record<string,string[]>)[d.date.slice(-2)]||[])} label={d.city}/><div className="j-periods">{[['上午',d.morning],['下午',d.afternoon],['晚上',d.evening]].map(([label,text])=><article key={label}><span>{label}</span><p>{text}</p></article>)}</div><details className="j-card j-schedule" open><summary>⏰ 時間安排</summary><ol className="j-timeline">{d.timeline.map(([time,text],i)=><li key={i}><time>{time}</time><span>{text}</span></li>)}</ol></details><PlaceStories plan={plan} date={d.date} city={d.city}/>{['2026-11-16','2026-11-17'].includes(d.date)&&<MedicaCard/>}<details className="j-card"><summary>🚆 交通與購票</summary><p>{d.transport}</p><ol>{d.transportSteps?.map((s,i)=><li key={i}>{s}</li>)}</ol><h4>🎟️ 購票方式</h4><ol>{d.ticketingSteps?.map((s,i)=><li key={i}>{s}</li>)}</ol>{d.ticketingNote&&<p>{d.ticketingNote}</p>}<div className="j-actions"><a className="j-link" href="https://int.bahn.de/en" target="_blank" rel="noreferrer">DB 查班次 ↗</a><a className="j-link" href="https://www.ns.nl/en" target="_blank" rel="noreferrer">NS 查班次 ↗</a><a className="j-link" href="https://9292.nl/en" target="_blank" rel="noreferrer">9292 接駁 ↗</a></div></details><article className="j-card"><h3>🍴 今天吃什麼</h3><p>{d.food}</p><button onClick={()=>{setCity(d.city.includes('海牙')?'海牙':d.city.includes('阿姆')?'阿姆斯特丹':d.city.includes('鹿特')?'鹿特丹':d.city==='科隆'?'科隆':'杜塞道夫');changeTab('food');}}>看餐廳與點心 →</button></article>{d.rain&&d.date>='2026-11-17'&&d.date<='2026-11-23'&&<details className="j-card"><summary>🌧️ 雨天走法</summary><p>{d.rain}</p></details>}{d.stay&&<p className="j-night">🛏️ 今晚住在 {d.stay}</p>}<label>當日備註<textarea value={(plan.notes as Record<string,string>)[d.date]||''} disabled={!ready} placeholder="集合時間、想吃的餐點、臨時調整…" onChange={e=>update({...plan,notes:{...plan.notes,[d.date]:e.target.value}})}/></label></div></section>}
 {tab==='stays'&&<section><p className="j-kicker">A PLACE TO COME HOME TO</p><h2>🛏️ 住宿</h2><p className="j-note">歐洲住宿共 NT$121,804 · 5 人均分約 NT$24,361／人 · 每人每晚約 NT$2,436。統一由靖宜代付，扣款安排如下。</p>{plan.stays.map((s,i)=><article className="j-stay" key={s.city}><p className="j-kicker">{s.city} · {s.checkIn.slice(5)} — {s.checkOut.slice(5)}</p><h3>{s.name}</h3><Gallery images={photos(plan.stayPhotos[i])} label={s.city+'住宿'}/><p>{s.address}</p><p><strong>{s.priceText}</strong></p><p>{s.perNightText}</p><p>{s.paymentText}</p>{s.booking&&<p className="j-note">{s.booking}</p>}<p>{s.accessNote}</p><div className="j-actions"><a className="j-link" href={s.bookingUrl} target="_blank" rel="noreferrer">查看住宿與房型 ↗</a><MapLink query={i===0?'Düsseldorf-Rath S Bahnhof':i===1?'Binnenrotteplein Rotterdam':s.name+' '+s.address}/></div><details><summary>🛒 附近買菜</summary>{s.nearbySupermarkets?.map(x=><p key={x}>{x} <MapLink query={x+' '+s.city}/></p>)}</details></article>)}</section>}
 {tab==='food'&&<section><p className="j-kicker">A TASTE OF THE CITY</p><h2>🍽️ 城市的味道</h2><div className="j-toggle"><button aria-pressed={foodView==='restaurants'} onClick={()=>setFoodView('restaurants')}>餐廳與點心</button><button aria-pressed={foodView==='shopping'} onClick={()=>setFoodView('shopping')}>購物</button></div>{foodView==='shopping'?<Shopping plan={plan}/>:<><p className="j-muted">午餐、點心與晚餐的名單，挑順路、想吃的就好。</p><div className="j-city-tabs">{plan.reference.foodLists.map(c=><button aria-pressed={city===c.city} key={c.city} onClick={()=>setCity(c.city)}>{c.city}</button>)}</div><div className="j-food-grid">{food?.items.map(f=><article className="j-food-card" key={f.name}>{f.image&&<Gallery images={f.images?.length?f.images:[f.image]} label={f.name+'・'+f.dish} showCaption={false}/>}<div><p className="j-kicker">{f.when}</p><h3>{f.name}</h3><p>{f.dish}</p>{f.intro&&<p>{f.intro}</p>}{'address' in f&&<p className="j-muted">{f.address}</p>}<MapLink query={f.name+' '+city}/></div></article>)}</div></>}</section>}
 {tab==='weather'&&<section><p className="j-kicker">RAIN, WIND & AUTUMN LIGHT</p><h2>🌦️ 天氣</h2><Gallery images={photos(['荷蘭11月 照片','杜賽道夫-3'])} label="十一月的城市"/><article className="j-card"><h3>杜賽道夫</h3><p>11 月平均高溫約 10°C、低溫約 4°C，月雨量約 62 mm。萊茵河畔風大，陰雨時體感更冷；防風外套、保暖中層與防水鞋最實用。</p><a className="j-link" href="https://www.timeanddate.com/weather/germany/dusseldorf" target="_blank" rel="noreferrer">查看杜賽道夫天氣 ↗</a></article><p>荷蘭 11 月適合分層穿衣，防風防水外套搭配保暖中層。以下是歷年氣候，並非旅遊當天的預報。</p><div className="j-grid">{climate.map(c=><article className="j-card" key={c.area}><h3>{c.area}</h3><p>{c.temperature}</p><p>月平均雨量 {c.rainMm} mm</p><p>≥ 0.1 mm 降水日：約 {Math.round(c.wetDays/30*100)}%</p><p>≥ 1 mm 降水日：約 {Math.round(c.rainDays/30*100)}%</p></article>)}</div><p>「有下過雨」不等於整天大雨；約 45–46% 的日子累積降雨達 1 mm，接近一半。出門前查看雨雷達，利用停雨空檔走戶外。</p>{weatherNotes.slice(2,6).map(x=><p key={x}>{x}</p>)}<a className="j-link" href="https://www.buienradar.nl/" target="_blank" rel="noreferrer">查看雨雷達 ↗</a></section>}
 {tab==='flights'&&<section><p className="j-kicker">ON OUR WAY</p><h2>🚆 航班・交通</h2><h3>哪些交通票先安排？</h3>{plan.transportBooking.map(t=><article className="j-card" key={t.name}><h4>{t.name}</h4><p>{t.text}</p></article>)}<div className="j-grid">{plan.reference.flights.map(f=><article className="j-card" key={f.group+f.route}><p className="j-kicker">{f.group}</p><h3>{f.route}</h3><p>{f.detail}</p></article>)}</div><article className="j-card"><h3>虹橋 → 浦東，需換機場</h3><p>四位旅伴 11/12 抵達虹橋後領行李、前往浦東，目標 22:00 前與益萁會合。向東航核對行李與報到截止時間。</p></article><MedicaCard/><article className="j-card"><h3>MEDICA · 11/16、11/17</h3><Gallery images={photos(['MEDICA','MEDICA-2'])} label="MEDICA"/><p>11/16、11/17 都住在杜賽道夫，可依會面進度參展。11/18 早上才退房，搭跨國火車前往鹿特丹。</p><p>U78 到 Messe Nord；展覽門票不包含公共交通，需另購車票。</p><MapLink query="Messe Düsseldorf Nord"/></article><article className="j-card"><h3>荷蘭搭車小提醒</h3><p>每人用自己的感應卡或裝置進出站，同一趟都用同一張卡。搭需附加票的 Intercity direct，還要在月台紅色 Supplement Pole 以同卡加購；普通進出站不會自動加上。</p><p>GVB 時數票只適用其涵蓋交通，不能拿來搭 NS 火車。72 小時從啟用時計算，11/23 下午機場交通可能已不在有效時間內。</p></article></section>}
 {tab==='ledger'&&ready&&<Ledger plan={plan} update={update}/>}{tab==='packing'&&ready&&<Packing plan={plan} update={update}/>}
 {tab==='apps'&&<section><p className="j-kicker">READY BEFORE TAKEOFF</p><h2>📱 要下載的 App</h2><div className="j-grid">{plan.reference.apps.map(a=><a className="j-card j-app" key={a.name} href={appLinks[a.name]||'https://www.google.com/'} target="_blank" rel="noreferrer"><span className={'j-app-icon j-app-'+a.name.split(' ')[0].toLowerCase()} aria-hidden="true">{appIcons[a.name]||'▦'}</span><div><p className="j-kicker">{a.country}</p><h3>{a.name}</h3><p>{a.why}</p><span className="j-link">前往下載頁 ↗</span></div></a>)}</div></section>}
 {tab==='ledger'&&<details className="j-card"><summary>資料備份</summary><div className="j-actions"><button disabled={!ready} onClick={()=>exportPlan('json')}>下載資料備份</button><button disabled={!ready} onClick={()=>file.current?.click()}>匯入資料備份</button><input hidden type="file" accept=".json,application/json" ref={file} onChange={e=>void importPlan(e.target.files?.[0])}/></div><p className="j-muted">資料儲存在目前瀏覽器；換手機前先下載備份。</p><button onClick={()=>{const raw=localStorage.getItem(KEY);if(raw)download(raw,'德荷旅遊-本機原始備份.json');}}>下載本機原始資料</button></details>}
 {status&&<p className="j-save" role="status">{status}</p>}</section><footer className="j-footer">德國、荷蘭之旅 · 2026<br/>一起出發，也留一點時間慢慢走。</footer></main>;
}

