'use client';
import {useEffect,useRef,useState} from 'react';
import {categories,categoryName,cents,defaultRates,money,totals,type Expense,type Plan} from '@/lib/journey';
const icons=['🍴','🚆','🏨','🎁','🎫','🧾'];
const blank=(name='益萁'):Expense=>({id:'',date:'2026-11-13',category:'吃飯',detail:'',amount:0,currency:'EUR',rate:36.75,payer:name,consumer:name,scope:'personal',note:'',status:'已付'});
export default function Ledger({plan,update}:{plan:Plan;update:(p:Plan)=>void}){
 const [viewer,setViewer]=useState('益萁'),[form,setForm]=useState<Expense>(()=>blank()),[message,setMessage]=useState(''),[remove,setRemove]=useState('');
 const picker=useRef<HTMLDetailsElement>(null),formElement=useRef<HTMLFormElement>(null);
 useEffect(()=>{try{const name=localStorage.getItem('de-nl-ledger-person');if(name&&plan.travelers.includes(name)){setViewer(name);setForm(blank(name));}}catch{}},[]);
 const amountTwd=(e:Expense)=>cents(e,defaultRates)/100;
 const visible=plan.expenses.filter(e=>e.scope!=='personal'||(e.consumer||e.payer)===viewer);
 const shared=visible.filter(e=>e.scope!=='personal'),personal=visible.filter(e=>e.scope==='personal');
 const sharedTotal=totals(shared,plan.people,defaultRates),personalTotal=totals(personal,1,defaultRates).total;
 const field=<K extends keyof Expense>(k:K,v:Expense[K])=>setForm(prev=>({...prev,[k]:v,...(['amount','currency'].includes(k)?{confirmedTwd:undefined}:{})}));
 function selectPerson(name:string){setViewer(name);setForm(blank(name));setMessage('');try{localStorage.setItem('de-nl-ledger-person',name);}catch{}}
 function save(e:React.FormEvent){e.preventDefault();if(!form.detail.trim()||!Number.isFinite(form.amount)||form.amount<=0||form.amount>1e9){setMessage('請填項目及正確金額。');return;}
 const item:Expense={...form,rate:defaultRates[form.currency],id:form.id||crypto.randomUUID(),category:categoryName(form.category),scope:form.scope||'personal',consumer:viewer,owner:viewer,detail:form.detail.trim()};
 update({...plan,expenses:form.id?plan.expenses.map(x=>x.id===form.id?item:x):[...plan.expenses,item]});setForm({...blank(viewer),date:form.date,currency:form.currency,scope:form.scope});setMessage('已儲存這筆帳目');}
 function canEdit(e:Expense){return (e.owner||(e.scope==='personal'?e.consumer:e.payer))===viewer;}
 function exportCsv(){const lines=[['日期','大項','項目','原幣金額','幣別','台幣小計','分攤方式','消費人','付款人','狀態','備註'],...visible.map(e=>[e.date,categoryName(e.category),e.detail,e.amount,e.currency,amountTwd(e),e.scope==='personal'?'個人消費':'公費均分',e.scope==='personal'?e.consumer:'全組',e.payer,e.status,e.note])];const csv='\ufeff'+lines.map(r=>r.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=viewer+'-德荷旅行帳本.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function groups(entries:Expense[]){return categories.filter(c=>entries.some(e=>categoryName(e.category)===c)).map(cat=>{const rows=entries.filter(e=>categoryName(e.category)===cat);return <details className="j-card j-ledger-group" key={cat}><summary><b>{icons[categories.indexOf(cat)]} {cat} · {rows.length} 筆</b><strong>NT${money(rows.reduce((n,e)=>n+amountTwd(e),0))}</strong></summary>{rows.map(e=><article className="j-entry" key={e.id}><p className="j-muted">{e.date} · {e.scope==='personal'?'個人消費':'全組 '+plan.people+' 人均分'}</p><h4>{e.detail}</h4><p><strong>NT${money(amountTwd(e))}</strong>{e.currency!=='TWD'&&<span> · {e.currency} {money(e.amount)}</span>}</p><p><b>{e.payer}</b> {e.bookingId?'代付安排':'付款'} · {e.status}</p>{e.scope!=='personal'&&<p>每人分攤 NT${money(Math.round(amountTwd(e)/plan.people))}</p>}{e.note&&<p>{e.note}</p>}{canEdit(e)&&<div className="j-actions"><button onClick={()=>{setForm(e);formElement.current?.scrollIntoView({block:'start'});}}>編輯</button><button onClick={()=>setRemove(e.id)}>刪除</button>{remove===e.id&&<><span>刪除這筆？</span><button onClick={()=>{update({...plan,expenses:plan.expenses.filter(x=>x.id!==e.id)});setRemove('');}}>確認刪除</button><button onClick={()=>setRemove('')}>保留</button></>}</div>}</article>)}</details>})}
 return <section><div className="j-section-heading"><h2>記帳</h2><button onClick={exportCsv}>下載明細</button></div><label>誰的帳本<select value={viewer} onChange={e=>selectPerson(e.target.value)}>{plan.travelers.map(t=><option key={t}>{t}</option>)}</select></label>
 <form ref={formElement} className="j-card j-form" onSubmit={save}><h3>{form.id?'編輯帳目':'新增一筆'}</h3><div className="j-grid"><label>金額<input required type="number" inputMode="decimal" min="0.01" max="1000000000" step="0.01" placeholder="0.00" value={form.amount||''} onChange={e=>field('amount',Number(e.target.value))}/></label><label>幣別<select value={form.currency} onChange={e=>field('currency',e.target.value)}>{[['EUR','歐元 EUR'],['TWD','台幣 TWD'],['CNY','人民幣 CNY'],['USD','美金 USD']].map(([c,label])=><option key={c} value={c}>{label}</option>)}</select></label></div><label>項目<input required maxLength={500} placeholder="例：科隆來回火車票" value={form.detail} onChange={e=>field('detail',e.target.value)}/></label>
 <div className="j-grid"><label>日期<input required type="date" value={form.date} onChange={e=>field('date',e.target.value)}/></label><div><label>大項</label><details ref={picker} className="j-category-picker"><summary>{icons[categories.indexOf(categoryName(form.category))]} {categoryName(form.category)} <span>⌄</span></summary><div className="j-category-options" role="group" aria-label="大項選單">{categories.map((c,i)=><button key={c} type="button" aria-pressed={form.category===c} onClick={()=>{field('category',c);if(picker.current)picker.current.open=false;}}>{icons[i]} {c}</button>)}</div></details></div></div>
 <div className="j-toggle" role="group" aria-label="分攤方式"><button type="button" aria-pressed={form.scope==='personal'} onClick={()=>field('scope','personal')}>👤 個人消費</button><button type="button" aria-pressed={form.scope==='shared'} onClick={()=>field('scope','shared')}>👥 公費均分</button></div><p className="j-note">本筆約 NT${money(amountTwd(form))} · {form.scope==='personal'?viewer+' 的消費':'每人約 NT$'+money(Math.round(amountTwd(form)/plan.people))}</p>
 <div className="j-grid"><label>誰先付<select value={form.payer} onChange={e=>field('payer',e.target.value)}>{[...new Set([...plan.travelers,form.payer])].filter(Boolean).map(t=><option key={t}>{t}</option>)}</select></label><label>付款狀態<select value={form.status} onChange={e=>field('status',e.target.value)}>{['已付','未付','待確認','扣款依安排'].map(t=><option key={t}>{t}</option>)}</select></label></div><label>備註（可留白）<input value={form.note} maxLength={2000} placeholder="例：5 人份、信用卡" onChange={e=>field('note',e.target.value)}/></label><button className="j-primary" type="submit">{form.id?'儲存修改':'加進帳本'}</button>{form.id&&<button type="button" onClick={()=>setForm(blank(viewer))}>取消編輯</button>}<p role="status">{message}</p></form>
 <h3>{viewer} 的明細</h3><div className="j-grid j-metrics"><article><span>個人消費</span><strong>NT${money(personalTotal)}</strong></article><article><span>公費應分攤・{plan.people} 人均分</span><strong>NT${money(sharedTotal.perPerson)}</strong></article></div><p className="j-muted">這裡是消費分攤，尚未扣除代墊款或彼此已轉帳金額。</p>{personal.length?groups(personal):<p className="j-card">尚未新增個人消費。</p>}<h3>公費明細・誰先付</h3>{groups(shared)}<p className="j-muted">機票按旅客列為個人消費，付款人依實際刷卡人記錄。三筆住宿已列入公費，城市稅包含在阿姆斯特丹住宿總額，請勿重複記入。帳目存在這台裝置的瀏覽器；家人各自選名字記帳，新增內容不會自動同步。需要彙整時可下載明細。</p></section>;
}

