export const guideNotice='整合使用者提供的《德荷行程-住宿超市美食總整理_1.md》（2026/9/9）。附件自述參考 Threads，但未附原貼文連結；以下餐廳屬二手推薦候選，未核實營業、價格與評分。官方查核僅適用另列的超市資料。';
export const guide=[
{city:'杜塞道夫',shopping:'11/13 入住 Bilk 的 Suitbertusstraße 18，優先在 Bilk 車站／Düsseldorf Arcaden 一帶找一般超市；11/14 補足週日食材。Little Tokyo 的亞洲超市留作外出午餐順路採買，不特別來回。',food:'午餐候選：Schumacher Alt（Oststr. 123）、Uerige（Berger Str. 1）德式料理；Little Tokyo 可選 Naniwa、Takumi；FOOD JUNG 作移動日外帶候選。Carlsplatz 可放週六回城後，勿排週日採買。每餐選一家即可。',alternatives:'11/17 展會後回中央站取行李搭車，沒有排隊名店空間；車站買簡餐及隔日早餐最穩妥。普通超市週日常休息，車站商店有例外。',verified:'DB 車站官網目前列 Düsseldorf Hbf EDEKA 每日 24 小時；在 14／15 月台間主通道，店面小，作基本補給。11 月營業仍須重查。',links:[['EDEKA 官方','https://www.bahnhof.de/duesseldorf-hbf/einkaufen-und-essen/edeka-im-bahnhof'],['REWE 官方門市搜尋','https://www.rewe.de/marktsuche/duesseldorf/']]},
{city:'科隆',shopping:'11/14 回杜塞道夫後補貨；一日版須把採買時間一起留出。',food:'午餐候選：Malzmühle 德式料理、Keule；小吃可試 Reibekuchen 馬鈴薯煎餅配蘋果泥。豬腳份量與價格現場確認，可討論分食。',alternatives:'保留原本半日／一日二選一；一日版加巧克力博物館，半日版只走大教堂、老城與河岸。',verified:'餐廳為附件候選，尚未核實指定日期營業。',links:[]},
{city:'鹿特丹',shopping:'11/18 參訪後買兩晚食材。優先查 Jumbo Botersloot 13–19；附件另列 AH Grotemarkt 98、AH Coolsingel 47。亞洲食材候選 Amazing Oriental（West-Kruiskade 26）及 Markthal 的 Wah Nam Hong。房源已確認為 Binnerotteplein／Meent 一帶，實際路程依房東門牌。',food:'Markthal 午餐可選炸魚；Bram Ladage 薯條、Dudok（Meent 88）蘋果派當共享點心。Little V、Hotel New York 可替換午餐；若去 Delfshaven，才考慮 Het Eethuisje van Delfshaven。',alternatives:'Depot 或 Delfshaven 二選一，取代 11/18 下午的舊港散步；不要加在全部原景點之後。Kinderdijk 僅作 11/22 風車村的替代思路，跨城動線需重排。',verified:'Jumbo 官網確認 Botersloot 門市；營業時間依當日門市頁。',links:[['Jumbo Botersloot 官方','https://www.jumbo.com/winkel/rotterdam/jumbo-rotterdam-botersloot']]},
{city:'海牙',shopping:'11/19 當天往返鹿特丹，晚餐用前一天買好的食材。',food:'午餐候選 Waroeng Padang Lapek（印尼料理）；咖啡候選 Bookstore Café、Single Estate。海邊炸魚只在天氣好、仍有胃口時選。',alternatives:'Mauritshuis 為主。Escher 或 Madurodam 可取代海邊行程，門票需另核對；和平宮以外觀短停為候選，不保證可入內。',verified:'新增餐廳與備案來自附件，尚未查核營業與指定時段。',links:[]},
{city:'阿姆斯特丹',shopping:'11/20 Cityden BoLo District 寄放行李後，採買選 Bos en Lommerplein 周邊一般超市（AH 等），11/22 用完剩餘食材。飯店 Minimart 供飲料與點心，完整晚餐食材去一般超市。',food:'Winkel 43 蘋果派、Van Stapele 餅乾、Fabel Friet 或 Vleminckx 薯條，擇一二共享。午餐可試 herring／kibbeling、The Pantry 或其他荷式料理；11/21 仍保留 Foodhallen 晚餐。小禮品選焦糖煎餅、巧克力、磁鐵；甘草糖先試吃。',alternatives:'不加入未核實的 Van Stapele 機場分店說法。Rijksmuseum 建議先訂時段，不把「只能網購」當規則。出境日是 11/23，11/25 是家人候選返台日。',verified:'Bos en Lommerplein 商圈官網列有 AH；入住後請櫃台指引最近超市，11月營業時間另查。',links:[['Bos en Lommerplein 商圈超市','https://www.bosenlommerplein.com/mkb-winkels/albert-heijn']]}
];
export function guideMarkdown(){return ['## 超市與美食',guideNotice,'住宿依使用者確認為 4＋3＋3＝10 晚，沒有缺兩晚；附件推算日期不採用。',...guide.flatMap(g=>[`### ${g.city}`,`採買：${g.shopping}`,`美食：${g.food}`,`替換選項：${g.alternatives}`,`查核：${g.verified}`,...g.links.map(([name,url])=>`- [${name}](${url})`)])].join('\n\n');}
